### ISSUE TITLE
What's your server name?

### ISSUE THREAD

**Issue by jedisct1** [evilvibes/dnscryptserver#1]
Just wondering how you would like your server to be called :)

**Comment by evilvibes** [comment]
ev-us should work.

**Comment by jedisct1** [comment]
Added :)

**Comment by evilvibes** [comment]
Awesome.

**Comment by evilvibes** [comment]
@jedisct1 I added one more server https://github.com/evilvibes/dnscryptserver 
Name can be ev-ca

**Comment by jedisct1** [comment]
2:44 AM, I really need to hit the sack now, but I'll add it in a couple hours.

**Comment by evilvibes** [comment]
No worries man no rush get them ZzzZzZzzzzzz

**Comment by jedisct1** [comment]
Added! Welcome to `ev-ca`!
